version: "3"

volumes:
  db_data: {}

services:
  db:
    container_name: "joos_db"
    image: mariadb
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "joos"
      MYSQL_USER: "joos"
      MYSQL_PASSWORD: "joos"
    networks:
      - joos_net
    ports:
      - "33306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./images/db/init-schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./images/db/init-data.sql:/docker-entrypoint-initdb.d/2.sql
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci"
    mem_limit: 256MB

  api:
    container_name: "joos_api"
    build: images/joos-api
    environment:
      - XDEBUG_MODE=develop,debug
    networks:
      - joos_net
    ports:
      - "4201:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./images/joos-api/src:/var/www/html/joos-api

  joos:
    container_name: "joos"
    build: "images/joos"
    networks:
      - joos_net
    ports:
    - "4200:4200"

networks:
  joos_net:
    name: joos_net