version: "3"

services:
  api:
    container_name: "joos_api"
    image: joos-api
    networks:
      - joos_net
    ports:
      - "80:80"
    volumes:
      - ../../../joos-api:/var/www/html/joos-api
networks:
  joos_net:
    external: true
    name: joos_net
