version: "3"

services:
  api:
    container_name: "joos_api"
    image: .
    networks:
      - joos_net
    ports:
      - "4201:80"
    volumes:
      - ../../../joos-api:/var/www/html/joos-api
networks:
  joos_net:
    external: true
    name: joos_net
